name: promote

on:
  workflow_dispatch:
  # push:
  #   branches: [master, main]

env:
  EKS_CLUSTER_BASENAME: "${{ vars.EKS_CLUSTER_BASENAME }}"

permissions: read-all

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # need to setup COMMIT_KEY (no workflow to trigger) with
        # ```sh
        # ssh-keygen -t ed25519 -f id_ed25519 -N "" -q -C ""
        # # can be done via WebUI
        # gh repo deploy-key add id_ed25519.pub -t "COMMIT_KEY" --allow-write
        # cat id_ed25519 | gh secret set "COMMIT_KEY" --app actions
        # rm id_ed25519.pub id_ed25519
        # ```
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          fetch-depth: "0" # to be able to use `git describe`` and retrieve tags
      - name: promote tag to next cluster/* level
        run: |
          .github/actions/promote.sh "$EKS_CLUSTER_BASENAME"
