// This file was generated by `mfy_api_generator`
// ⚠️  HANDLE WITH CARE

use serde::{Deserialize, Serialize};

use crate::domain::AnimalType;

/// The [`CreateAnimal`]
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CreateAnimal {
    /// The r#type
    #[serde(rename = "type")]
    pub r#type: AnimalType,
    /// The name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The cute
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cute: Option<bool>,
}
