// This file was generated by `mfy_api_generator`
// ⚠️  HANDLE WITH CARE

use serde::{Deserialize, Serialize};

/// The [`Dog`]
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub struct Dog {
    /// The id
    pub id: String,
    /// The name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The cute
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cute: Option<bool>,
}
