// This file was generated by `mfy_api_generator`
// ⚠️  HANDLE WITH CARE

mod animal_type;
mod create_animal;
mod dog;

pub use self::animal_type::*;
pub use self::create_animal::*;
pub use self::dog::*;
