# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: none
DISABLE:
- COPYPASTE
- SPELL
DISABLE_LINTERS:
- DOCKERFILE_DOCKERFILELINT
- MARKDOWN_MARKDOWN_LINK_CHECK
- REPOSITORY_GIT_DIFF
- REPOSITORY_SYFT
- RUST_CLIPPY
FILTER_REGEX_EXCLUDE: (\.gitignore)||(\.lock)|(\.ndjson)|(\.pdf)|(\.csv)|(\.zip)|(\.tar)|(\.ipynb)|(settings\.py)|(\.vscode/settings\.json)
MARKDOWN_FILTER_REGEX_EXCLUDE: (license\.md)
PRINT_ALPACA: false
REPOSITORY_SECRETLINT_ARGUMENTS:
- --secretlintignore
- .gitignore
REPOSITORY_TRIVY_ARGUMENTS:
- --skip-files
- .devcontainer/Dockerfile
RUST_CLIPPY_ARGUMENTS:
- --workspace
- --all-features
- --all-targets
- --
- --deny warnings
- --allow deprecated
SPELL_FILTER_REGEX_INCLUDE: \.md$
YAML_FILTER_REGEX_EXCLUDE: (devops/chart/templates)
