# ./spec.v1.yml
openapi: 3.0.2
info:
  title: My Project
  version: "0.1.0"
  description: Getting started with mfy_api_generator
  contact:
    name: Me
    email: malikeljaouadi@gmail.com
servers:
  - url: "http://wefox-ai-my-project.wai.svc.cluster.local"
    description: inside
paths:
  "/ai/my-project/animals":
    post:
      description: Post request to get animals
      tags: ["animals", "testing"]
      operationId: "1"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAnimal"
      responses:
        "200":
          description: The craeted animal id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnimalId"
  "/ai/my-project/animals/dogs/{id}":
    get:
      description: Post request to get animals
      tags: ["animals", "testing"]
      operationId: "2"
      parameters:
        - $ref: "#/components/parameters/AnimalId"
      responses:
        "200":
          description: The created animal id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dog"
components:
  parameters:
    AnimalId:
      name: id
      required: true
      in: path
      schema:
        $ref: "#/components/schemas/AnimalId"
  schemas:
    CreateAnimal:
      type: object
      required:
        - type
      properties:
        type:
          $ref: "#/components/schemas/AnimalType"
        name:
          type: string
        cute:
          type: boolean
    AnimalType:
      type: string
      enum:
        - cat
        - dog
        - possum
    AnimalId:
      type: string
    Dog:
      type: object
      required:
        - id
      properties:
        id:
          $ref: "#/components/schemas/AnimalId"
        name:
          type: string
        cute:
          type: boolean
