// This file was generated by `mfy_api_generator`
// ⚠️  HANDLE WITH CARE

use axum::extract::{Path, State};
use wai_axum_extra::prelude::*;

use crate::domain::Dog;
use crate::service::{MyProjectError, MyProjectState};

/// Handler for GET /ai/my-project/animals/dogs/id
#[axum_macros::debug_handler]
#[tracing::instrument(skip(_state))]
pub async fn handler_get_ai_my_project_animals_dogs_id(
    State(_state): State<MyProjectState>,
    Path(id): Path<String>,
) -> EndpointResult<Dog, MyProjectError> {
    Ok(EndpointReturn::NotImplemented)
}
