// This file was generated by `mfy_api_generator`
// ⚠️  HANDLE WITH CARE

use axum::routing::{get, post};
use axum::Router;

use crate::service::MyProjectState;

mod get_ai_my_project_animals_dogs_id;
mod post_ai_my_project_animals;

pub use self::get_ai_my_project_animals_dogs_id::*;
pub use self::post_ai_my_project_animals::*;

///The application Router
pub fn build_application_router() -> Router<MyProjectState> {
    Router::new().nest(
        "/ai/my-project/animals",
        Router::new()
            .route("/", post(handler_post_ai_my_project_animals))
            .route("/dogs/:id", get(handler_get_ai_my_project_animals_dogs_id)),
    )
}
