// This file was generated by `mfy_api_generator`
// ⚠️  HANDLE WITH CARE

use axum::extract::State;
use wai_axum_extra::prelude::*;

use crate::domain::CreateAnimal;
use crate::service::{MyProjectError, MyProjectState};

/// Handler for POST /ai/my-project/animals
#[axum_macros::debug_handler]
#[tracing::instrument(skip(_state))]
pub async fn handler_post_ai_my_project_animals(
    State(_state): State<MyProjectState>,
    Json(create_animal): Json<CreateAnimal>,
) -> EndpointResult<String, MyProjectError> {
    Ok(EndpointReturn::NotImplemented)
}
